#!/bin/bash

fun_fun(){
        clear
    echo -e "\e[1;33m________________________________________\e[0m" #orange
    echo ""
    echo -e "\e[7;1;5;33m U P D A T I N G  I N  P R O G R E S S \e[0m" 
    echo -e "\e[1;33m________________________________________\e[0m"
    echo ""
    sudo apt-get update -y
    clear
    echo -e "\e[1;31m________________________________________\e[0m" #red
    echo ""
    echo -e "\e[7;1;5;31m U P G R A D E   I N   P R O G R E S S \e[0m"
    echo -e "\e[1;31m________________________________________\e[0m"
    sleep 0.5s
    echo ""
    sudo apt-get upgrade -y
    clear
    echo -e "\e[1;35m_____________________________________________________\e[0m" #purple
    echo ""
    echo -e "\e[7;1;5;35m D I S T R O - U P G R A D E   I N   P R O G R E S S \e[0m"
    echo -e "\e[1;35m_____________________________________________________\e[0m"
    sleep 0.5s
    echo ""
    sudo apt-get dist-upgrade -y
    clear
    echo -e "\e[1;34m_________________________________________________\e[0m"  #blue
    echo ""
    echo -e "\e[7;1;5;34m F U L L - U P G R A D E   I N   P R O G R E S S \e[0m"
    echo -e "\e[1;34m_________________________________________________\e[0m"
    echo ""
    sleep 2s
    sudo apt-get full-update -y
    clear
    echo -e "\e[1;32m_______________________________________\e[0m" #green
    echo ""
    echo -e "\e[7;1;5;32m C L E A N I N G  I N  P R O G R E S S \e[0m"
    echo -e "\e[1;32m_______________________________________\e[0m"
    sleep 0.5s
    echo ""
    sudo apt-get autoremove -y
    clear
    echo -e "\e[1;33m__________________________________________\e[0m"
    echo ""
    echo -e "\e[7;1;5;33m            A L L  D O N E            \e[0m"
    echo -e "\e[1;33m___________________________________________\e[0m"
    sleep 1s
    clear
    exit
}
check_disto=/etc/os-release
if grep -q "Ubuntu" $check_disto || grep -q "Parrot" $check_disto || grep -q "kali" $check_disto || grep -q "debain" $check_disto || grep -q "Pop" $check_disto 
then
fun_fun
fi

if grep -q "Arch" $check_disto
then
# based on arch
    clear
    echo -e "\e[1;33m________________________________________\e[0m" #orange
    echo ""
    echo -e "\e[7;1;5;33m U P D A T I N G  I N  P R O G R E S S \e[0m" 
    echo -e "\e[1;33m________________________________________\e[0m"
    echo ""
    sudo pacman -Syc -y
    clear
    exit
fi

if grep -q "Red hat" $check_disto || grep -q "Rpm" $check_disto || grep -q "Red-hat" $check_disto || grep -q "rpm" $check_disto || grep -q "red-hat" $check_disto
then
# based on rpm
    clear
    echo -e "\e[1;33m________________________________________\e[0m" #orange
    echo ""
    echo -e "\e[7;1;5;33m U P D A T I N G  I N  P R O G R E S S \e[0m" 
    echo -e "\e[1;33m________________________________________\e[0m"
    echo ""
    sudo yum update -y
    clear
    echo -e "\e[1;31m________________________________________\e[0m" #red
    echo ""
    echo -e "\e[7;1;5;31m U P G R A D E   I N   P R O G R E S S \e[0m"
    echo -e "\e[1;31m________________________________________\e[0m"
    sleep 0.5s
    echo ""
    sudo yum upgrade -y
    clear
    echo -e "\e[1;32m_______________________________________\e[0m" #green
    echo ""
    echo -e "\e[7;1;5;32m C L E A N I N G  I N  P R O G R E S S \e[0m"
    echo -e "\e[1;32m_______________________________________\e[0m"
    sleep 0.5s
    echo ""
    sudo yum autoclean -y
    clear
    echo -e "\e[1;33m__________________________________________\e[0m"
    echo ""
    echo -e "\e[7;1;5;33m            A L L  D O N E            \e[0m"
    echo -e "\e[1;33m___________________________________________\e[0m"
    sleep 1s
    clear
    exit
fi
